import React from "react";
import "../TopUp/TopUp.css";
const TopUpHistory = () => {
  return (
    <div className="container-fluid TopUpHistory">
      <div>
        <h2>Top Up/Top Up History</h2>
      </div>
      <div class="container-fluid">
        <div>
          <h2>Top Up History</h2>
        </div>
        <table>
          <thead>
            <tr>
              <th>Sr.No.</th>
              <th>Reg. Date</th>
              <th>User ID</th>
              <th>User Name</th>
              <th>$</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1</td>
              <td>4/18/2024</td>
              <td>MTF540844</td>
              <td>John</td>
              <td>Left</td>
            </tr>
            <tr>
              <td>1</td>
              <td>4/18/2024</td>
              <td>MTF540844</td>
              <td>John</td>
              <td>Left</td>
            </tr>
            <tr>
              <td>1</td>
              <td>4/18/2024</td>
              <td>MTF540844</td>
              <td>John</td>
              <td>Left</td>
            </tr>
            <tr>
              <td>1</td>
              <td>4/18/2024</td>
              <td>MTF540844</td>
              <td>John</td>
              <td>Left</td>
            </tr>
            <tr>
              <td>1</td>
              <td>4/18/2024</td>
              <td>MTF540844</td>
              <td>John</td>
              <td>Left</td>
            </tr>
            <tr>
              <td>1</td>
              <td>4/18/2024</td>
              <td>MTF540844</td>
              <td>John</td>
              <td>Left</td>
            </tr>
            <tr>
              <td>1</td>
              <td>4/18/2024</td>
              <td>MTF540844</td>
              <td>John</td>
              <td>Left</td>
            </tr>
            <tr>
              <td>1</td>
              <td>4/18/2024</td>
              <td>MTF540844</td>
              <td>John</td>
              <td>Left</td>
            </tr>
            <tr>
              <td>1</td>
              <td>4/18/2024</td>
              <td>MTF540844</td>
              <td>John</td>
              <td>Left</td>
            </tr>
            <tr>
              <td>1</td>
              <td>4/18/2024</td>
              <td>MTF540844</td>
              <td>John</td>
              <td>Left</td>
            </tr>
            <tr>
              <td>1</td>
              <td>4/18/2024</td>
              <td>MTF540844</td>
              <td>John</td>
              <td>Left</td>
            </tr>
            <tr>
              <td>1</td>
              <td>4/18/2024</td>
              <td>MTF540844</td>
              <td>John</td>
              <td>Left</td>
            </tr>
            <tr>
              <td>1</td>
              <td>4/18/2024</td>
              <td>MTF540844</td>
              <td>John</td>
              <td>Left</td>
            </tr>
            <tr>
              <td>1</td>
              <td>4/18/2024</td>
              <td>MTF540844</td>
              <td>John</td>
              <td>Left</td>
            </tr>
            <tr>
              <td>1</td>
              <td>4/18/2024</td>
              <td>MTF540844</td>
              <td>John</td>
              <td>Left</td>
            </tr>

            <tr>
              <td>1</td>
              <td>4/18/2024</td>
              <td>MTF540844</td>
              <td>John</td>
              <td>Left</td>
            </tr>
            <tr>
              <td>1</td>
              <td>4/18/2024</td>
              <td>MTF540844</td>
              <td>John</td>
              <td>Left</td>
            </tr>
            <tr>
              <td>1</td>
              <td>4/18/2024</td>
              <td>MTF540844</td>
              <td>John</td>
              <td>Left</td>
            </tr>
            <tr>
              <td>1</td>
              <td>4/18/2024</td>
              <td>MTF540844</td>
              <td>John</td>
              <td>Left</td>
            </tr>
            <tr>
              <td>1</td>
              <td>4/18/2024</td>
              <td>MTF540844</td>
              <td>John</td>
              <td>Left</td>
            </tr>
            <tr>
              <td>1</td>
              <td>4/18/2024</td>
              <td>MTF540844</td>
              <td>John</td>
              <td>Left</td>
            </tr>

            <tr>
              <td>1</td>
              <td>4/18/2024</td>
              <td>MTF540844</td>
              <td>John</td>
              <td>Left</td>
            </tr>
            <tr>
              <td>1</td>
              <td>4/18/2024</td>
              <td>MTF540844</td>
              <td>John</td>
              <td>Left</td>
            </tr>
            <tr>
              <td>1</td>
              <td>4/18/2024</td>
              <td>MTF540844</td>
              <td>John</td>
              <td>Left</td>
            </tr>
            <tr>
              <td>1</td>
              <td>4/18/2024</td>
              <td>MTF540844</td>
              <td>John</td>
              <td>Left</td>
            </tr>
            <tr>
              <td>1</td>
              <td>4/18/2024</td>
              <td>MTF540844</td>
              <td>John</td>
              <td>Left</td>
            </tr>
            <tr>
              <td>1</td>
              <td>4/18/2024</td>
              <td>MTF540844</td>
              <td>John</td>
              <td>Left</td>
            </tr>
            <tr>
              <td>1</td>
              <td>4/18/2024</td>
              <td>MTF540844</td>
              <td>John</td>
              <td>Left</td>
            </tr>
            <tr>
              <td>1</td>
              <td>4/18/2024</td>
              <td>MTF540844</td>
              <td>John</td>
              <td>Left</td>
            </tr>
            <tr>
              <td>1</td>
              <td>4/18/2024</td>
              <td>MTF540844</td>
              <td>John</td>
              <td>Left</td>
            </tr>
            <tr>
              <td>1</td>
              <td>4/18/2024</td>
              <td>MTF540844</td>
              <td>John</td>
              <td>Left</td>
            </tr>
            <tr>
              <td>1</td>
              <td>4/18/2024</td>
              <td>MTF540844</td>
              <td>John</td>
              <td>Left</td>
            </tr>
            <tr>
              <td>1</td>
              <td>4/18/2024</td>
              <td>MTF540844</td>
              <td>John</td>
              <td>Left</td>
            </tr>
            <tr>
              <td>1</td>
              <td>4/18/2024</td>
              <td>MTF540844</td>
              <td>John</td>
              <td>Left</td>
            </tr>
            <tr>
              <td>1</td>
              <td>4/18/2024</td>
              <td>MTF540844</td>
              <td>John</td>
              <td>Left</td>
            </tr>
            <tr>
              <td>1</td>
              <td>4/18/2024</td>
              <td>MTF540844</td>
              <td>John</td>
              <td>Left</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  );
};

export default TopUpHistory;
