import React from 'react'
import '../MyNetwork/MyNetwork.css'
const DirectTeam = () => {
  return (
<div className='container-fluid MyNetwork'>
    <div>
        <h2>My Network/Direct Team</h2>
    </div>
<div className ="container-fluid p-3 w-100">
    <div>
      <h2 className='w-100'>Direct Team</h2>
    </div>
  <table >
    <thead>
      <tr>
        <th>Sr. No.</th>
        <th>Reg. Date</th>
        <th>User ID</th>
        <th>User Name</th>
        <th>Position</th>
        <th>Package</th>
        <th>Active Date</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
      <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>

      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr><tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>

      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>

      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr><tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr><tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr><tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr><tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr><tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr><tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr><tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr><tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr><tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>
      <tr>
        <td>1</td>
        <td>4/18/2024</td>
        <td>MTF540844</td>
        <td>John</td>
        <td>Left</td>
        <td>0</td>
        <td></td>
      </tr>

    </tbody>
  </table>
</div>
</div>
  )
}

export default DirectTeam