import React from "react";
import "../MyNetwork/MyNetwork.css";
const DirectTeam = () => {
  return (
    <div className="container-fluid MyNetwork">
      <div>
        <h2>My Network/Downline Team</h2>
      </div>
      <div className="container-fluid">
        <div>
          <h2>Downline Team</h2>
        </div>
        <div className="table-responsive " style="overflow-x:auto;">
          <table>
            <thead>
              <tr>
                <th>Sr. No.</th>
                <th>Reg. Date</th>
                <th>User ID</th>
                <th>User Name</th>
                <th>Sponser ID</th>
                <th>Sponser Name</th>
                <th>Active Date</th>
                <th>Position</th>
                <th>Package</th>
                <th>Level</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>

              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>

              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>

              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
              <tr>
                <td>1</td>
                <td>4/18/2024</td>
                <td>MTF540844</td>
                <td>John</td>
                <td>Left</td>
                <td>0</td>
                <td></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default DirectTeam;
